### ISSUE TITLE
luckperms support - nice to see!

### ISSUE THREAD

**Issue by TymekSL** [rudynakodach/WebhookIntegrations#12]
Luckperms placeholders like [Owner] joined the game!
[but without colors]

**Comment by rudynakodach** [comment]
https://luckperms.net/wiki/Placeholders

Luckperms already has a placeholder extension for PAPI. Install `Expansion-LuckPerms.jar` and put it in the expansion folder. Placeholders are listed on the website above.

**Comment by TymekSL** [comment]
whats the placeholder to see this in the discord message?

**Comment by rudynakodach** [comment]
%luckperms_prefix%
OR
%luckperms_suffix%

**Comment by TymekSL** [comment]
![350729436_147667228303967_404592902619075970_n](https://github.com/rudynakodach/WebhookIntegrations/assets/90581745/c470f952-74f9-44ab-96f3-502ae53ab7fc)

no to ładnie nie wygląda xD

**Comment by rudynakodach** [comment]
W takim wypadku poszukaj innych rozszerzeń do PAPI dla Luckperms albo użyj %vault_rank% (`/papi ecloud download Vault`)

**Comment by TymekSL** [comment]
a czy luckperms_group (czli bez kolorów) zadziała? w sensie czy moge używać wszystkichplaceholderów lp czy tylko tych 2

**Comment by TymekSL** [comment]
niestety, odpowiadając sobie na to pytanie - nie, nie zadziała i wyświetla [%luckperms_group% nick, szkoda bo te kolory są ohydne i nie wiem po co ten support lp
