### ISSUE TITLE
config bug 

### ISSUE THREAD

**Issue by TymekSL** [rudynakodach/WebhookIntegrations#14]
check-for-updates: true
auto-update: true

# The URL for your Discord Webhook.
# This cannot be empty!
webhookUrl: "XYZengjZ4lSpK4tdw7tau_s8frTpZc"

# The plugin selects the language of the system the plugin is running on.
# Set this to your language you want the plugin to be in, false otherwise. Should be formatted like this: "en_US"
# NOTE: The language you will set it to MUST be in the lang.yml file. You can easily add new languages by copying existing ones and changing texts.
language-override: false

# set this to false if you don't want to send messages to the webhook
isEnabled: true

# Events will be ignored for vanished players and no message will be sent to the webhook.
disableForVanishedPlayers: true

# Replaces every occurrence of each word to their corresponding values
# e.g. "@everyone" to "everyone"
# You should wrap censored phrases in "quotes".
censoring:
  "@everyone": "everyone"
  "@here": "here"

useRegexCensoring: false
# Works like regular censoring but compares text to the provided regex (regular expression) patters. You really shouldn't use this unless you get to know regex.
regexCensoring:
  "\<\@[0-9]+\>": ""

# You can ping someone using their id like this: <@id> (for instance <@795204175314272>)
# Setting this to true removes this ability by removing the force-ping from the message completely.
remove-force-pings: true
# The same thing as in user pings but for channels: <#id> (for instance <#4832407155909>)
# Setting this to true removes this ability by removing the force-channel-ping from the message completely.
remove-force-channel-pings: true

# The same thing here. Removes the ability to use the <@&id> syntax to ping roles.
remove-force-role-pings: true

# Date format used for the $time$ placeholder. All formats: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
date-format: "HH:mm:ss"

# The timezone used for timestamps in the $timestamp$ placeholder.
timezone: "UTC"

#END OF FILE

In the console:

[02:10:00 WARN]: [WebhookIntegrations] Attempted to send a message to an empty webhook URL! Use /setUrl or disable the event in the config!

**Comment by rudynakodach** [comment]
Set the webhook URL to a valid URL (looking like https://discord.com/api/webhooks/XXXX/XXXXXXXXX) and restart or use `/wi reload`

**Comment by TymekSL** [comment]
no zrobiłem tak

**Comment by rudynakodach** [comment]
Taka wiadomość, jaką widzisz w konsoli jest wyświetlana tylko wtedy, gdy `webhookUrl` nie jest ustawiony.
