### ISSUE TITLE
null when making /seturl

### ISSUE THREAD

**Issue by TymekSL** [rudynakodach/WebhookIntegrations#15]
I have 3x null informations when trying setting url trough command because trough config and restarting there is error [latest issue] 

Pl bo łatwiej xd 
Próbowałem ustawic webhook komendą i wyskakuje mi 3x null, jeden napis na niebiesko i 2 na zielono , 
![350760910_2916912288438743_6911599577189419839_n](https://github.com/rudynakodach/WebhookIntegrations/assets/90581745/3a28fe33-e333-47fc-bdac-254106c356c8)

**Comment by rudynakodach** [comment]
Sprawdź konsole, jeżeli jest tam też null, na początku włączania plugina jest wiadomość `Hooked to XX_XX` gdzie `XX_XX` to język, który wybrał plugin. Jeżeli on nie istnieje w `lang.yml`, zrób backupa (`/wi config savebackup`) i wpisz `/wi config reset confirm`, a potem `/wi reload`

**Comment by TymekSL** [comment]
Teraz mam problem z configiem (nowy issue) i jest tylko wnehook nie ma żadnej konfiguracji

**Comment by rudynakodach** [comment]
> Teraz mam problem z configiem (nowy issue) i jest tylko wnehook nie ma żadnej konfiguracji

To nie jest związane z tym problemem.
