### ISSUE TITLE
[few Bugs found]

### ISSUE THREAD

**Issue by TymekSL** [rudynakodach/WebhookIntegrations#16]
Found few Bugs:
1. On the spigot there is mistake "integrtions" 
2. After set the URL , opening the config and i have ONLY webhook URL - 0 configurations
3. Message only when server is stopped although there is join msg set, start msg set , why?

**Comment by rudynakodach** [comment]
1. Fixed
2. Can't reproduce
3. Can't reproduce

Use the latest version and try again.

**Comment by TymekSL** [comment]
???? Why  marked as Invalid. All is good, on the config file have only webhook, give me discord i will send in DC

**Comment by TymekSL** [comment]
![Uploading orca-image-911381389.jpeg…]()

**Comment by TymekSL** [comment]
![orca-image-1368451511](https://github.com/rudynakodach/WebhookIntegrations/assets/90581745/eb52e7aa-6593-41cb-a3d7-a3a77837935f)

**Comment by TymekSL** [comment]
![orca-image-911381389](https://github.com/rudynakodach/WebhookIntegrations/assets/90581745/5f067dfd-386d-4e96-a9b8-d40ed074b965)

**Comment by TymekSL** [comment]
18 hours no reply, hmmmm

**Comment by TymekSL** [comment]
commented last week...

**Comment by rudynakodach** [comment]
> commented last week...

Nie podałeś jakiej wersji plugina używasz, oprogramowania serwera, wersji Minecrafta i jak doszedłeś do otrzymania błędu.
Próbowałem na wiele sposobów otrzymać błędy, jakie miałeś i nie udało mi się odtworzyć ani jednego.

Postaw się w moim miejscu. Mam naprawić coś, co nie wiem jak się stało. Z resztą, błędy numer 2 i 3, jakie opisałeś, nie wydają się mi nawet i możliwe. Spróbuj użyć najnowszej wersji. Jeżeli nadal coś nie działa to podaj wymagane dane i zacznę nad tym pracować.

Wiedz, że jeżeli wystąpi jakiś błąd podczas wysyłania wiadomości do Discorda, wszystko zostanie wysłane w konsoli. Jeżeli coś się nie wysłało to jest szansa, że będzie wiadomo dlaczego patrząc w logi.

Pytałeś się wcześniej dlaczego tag `invalid`. Odpowiadając na to pytanie, nie podałeś najpotrzebniejszych rzeczy. Nie miałem wystarczająco informacji, żeby móc dotrzeć do sedna błędu. Z tego co napisałeś wynika to, że coś nie działa. Po dokładnej analizie kodu i kodu źródłowego PaperMC, błędy jakie otrzymałeś nie wydają się nawet logiczne.
