### ISSUE TITLE
WI suggestion.

### ISSUE THREAD

**Issue by TymekSL** [rudynakodach/WebhookIntegrations#18]
1. Reload command trough console too 
2. /wi status - when plugin is not setup - red message "PLUGIN IS NOT CONFIGURED" when all is ok green msg "PLUGIN WORKING CORRECTLY" ! becuase when there is error can't know how to fix it

**Comment by rudynakodach** [comment]
1. I will work on it once I have time to spare.
2. `/wi analyze`

**Comment by TymekSL** [comment]
+ one moee:
When player back from Vanish there should be message that he join to the server

**Comment by TymekSL** [comment]
.

**Comment by TymekSL** [comment]
@rudynakodach

**Comment by rudynakodach** [comment]
> * one moee:
>   When player back from Vanish there should be message that he join to the server

I'm already working on it, be patient.

**Comment by TymekSL** [comment]
Hmmm...0 odpowiedzi + usuwanie komentarzy
@rudynakodach do ty odwalasz jakbym mógł wiedzieć co?

**Comment by rudynakodach** [comment]
> Hmmm...0 odpowiedzi + usuwanie komentarzy @rudynakodach do ty odwalasz jakbym mógł wiedzieć co?

"@rudynakodach" i "." to nie są istotne komentarze. Odpisałem, że pracuję nad tym i usunąłem niepotrzebne rzeczy.
Niedługo to powinno znaleźć się w pluginie, najprawdopodobniej w następnej wersji.

**Comment by TymekSL** [comment]
kiedy +/- można tej aktualizacji się spodziewać? bo była aktualizacja tylko z fixem a pisałem to 3 tygodnie temu...

**Comment by rudynakodach** [comment]
> kiedy +/- można tej aktualizacji się spodziewać? bo była aktualizacja tylko z fixem a pisałem to 3 tygodnie temu...

Nie mam pojęcia, nie jest to takie proste i czasu też nie mam zbyt dużo.

**Comment by TymekSL** [comment]
serio? jeszcze 3 tygodnie temu stwierdziłeś że będzie w następnej aktualizacji widze fajne zmiany zdań

**Comment by TymekSL** [comment]
import de.myzelyam.api.vanish.PlayerHideEvent;
import de.myzelyam.api.vanish.PlayerShowEvent;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerQuitEvent;

public class PremiumVanish implements Listener {
  @EventHandler(priority = EventPriority.MONITOR)
  public void onPlayerUnVanish(PlayerShowEvent event) {
    Player player = event.getPlayer();
    JoinEvent joinEvent = new JoinEvent(true);
    PlayerJoinEvent join = new PlayerJoinEvent(player, null);
    joinEvent.execute(join);
  }
  
  @EventHandler(priority = EventPriority.MONITOR)
  public void onPlayerVanish(PlayerHideEvent e) {
    Player p = e.getPlayer();
    QuitEvent quitEvent = new QuitEvent(true);
    PlayerQuitEvent quit = new PlayerQuitEvent(p, null);
    quitEvent.execute(quit);
  }
}


wystarczy wkleić do pluginu i zrobić aktualizacje ale spoko skoro takie wielkie problemy sprawia ci skopiowanie api xd

**Comment by rudynakodach** [comment]
Po sprawdzeniu, jak plugin z tym działa, stwierdziłem, że jest to niepotrzebne i nie zostanie dodane. Niektóre większe serwery ukrywają graczy (to samo co robi vanish) by zwiększyć wydajność gry m.in. słabszym komputerom. Jeżeli jest to tak proste, jak skopiowanie ~API~ pliku kodu i wklejenie go, to zrób swojego forka i zmień co potrzebujesz.
