### ISSUE TITLE
no message when server is starting

### ISSUE THREAD

**Issue by TymekSL** [rudynakodach/WebhookIntegrations#19]
I don't have message when server is starting. Option is set to true but on discord - 0 messages

**Comment by DravenSA** [comment]
get error
```
ERROR]: [WebhookIntegrations] Plugin WebhookIntegrations v4.1.2 has failed to register events for class rudynakodach.github.io.webhookintegrations.Events.Webhook.OnPlayerChat because io/papermc/paper/event/player/AsyncChatEvent does not exist.
```
and 
```
Caused by: java.lang.NullPointerException: Cannot invoke "rudynakodach.github.io.webhookintegrations.Modules.MessageConfiguration.canAnnounce(String)" because the return value of "rudynakodach.github.io.webhookintegrations.Modules.MessageConfiguration.get()" is null

```
hope this helps fault find

**Comment by rudynakodach** [comment]
You didn't include an exception stack so I don't know where (and how) the error occured. Also this refers to the player chat event, not the server start one.

The error you get seems weird. What minecraft version is the server running? Is your server running on PaperMC? If the issue persists, please open a new bug report.

**Comment by rudynakodach** [comment]
Turns out I forgot to register the event for `ServerLoadEvent`. Fix coming soon.
