### ISSUE TITLE
WI suggestions.

### ISSUE THREAD

**Issue by roltairtheprotogen** [rudynakodach/WebhookIntegrations#22]
Add support to:
1. Log console output
2. Log commands ran on the console
3. Log commands ran via players

**Comment by rudynakodach** [comment]
This already is a thing. When a player uses a server command, there is console output indicating which player used what command. If you want to log console commands used, you can donwload a plugin called **Essentials**.

The plugin also logs all errors when they occur, I think there is no need to flood the console with "Succesfuly sent message to webhook" each time anything happens.
