### ISSUE TITLE
WI suggestion. Embed msg on command

### ISSUE THREAD

**Issue by LadyHaley** [rudynakodach/WebhookIntegrations#25]
# Suggestion
This is a template for submitting a suggestion.

## The Idea
What is your idea?
Have a command to send an embed pre created from a json file
What is its purpose?
Makes the plugin even more versitile

If implemented, how would it be used?
I could have other plugin run the commands on demand in various contexts
## Why should it be added?
Would be fun
...

## Reference data
If your idea comes from a source of some kind, please provide the sources below.

**Comment by LadyHaley** [comment]
For clarification, I would like to do things like this with mostly minigame plugins
![2024-02-28-16-38-51-firefox](https://github.com/rudynakodach/WebhookIntegrations/assets/3754909/4eb0e93b-74c2-46d0-b0c4-1724a9082921)

**Comment by LadyHaley** [comment]
The idea is you'd set the embed in the messages file then with a command like /wi send template "template name" and it would send it into the discord. It would probably help with organisation tho if we could have a templates folder with a bunch of different json or yml files in there to help organise different msgs that way

**Comment by rudynakodach** [comment]
I like it - I'm on it!

**Comment by LadyHaley** [comment]
In the interest of placeholder usage, it might be a good idea to have the msg inherit the player who ran the command for placeholders so things like username and uuid placeholders can be used

**Comment by rudynakodach** [comment]
Done.
The feature is used by a command `/wi template send (template name)`.
Make sure to check `WebhookIntegrations/templates.yml` to see what this update has to offer.
