### ISSUE TITLE
Again scary errors(

### ISSUE THREAD

**Issue by SODANIKS** [rudynakodach/WebhookIntegrations#3]
![image](https://user-images.githubusercontent.com/61115286/220722182-e2e3ae0c-ce7e-45d9-a40e-5296510e6241.png)

**Comment by rudynakodach** [comment]
This looks like an internal error to me. Maybe you're using an older version than 1.12.2 and events work different in that version I suppose? The plugin supports version ranging from 1.12.2 to the latest release. Can you tell me what MInecraft version is the server running?

**Comment by SODANIKS** [comment]
> This looks like an internal error to me. Maybe you're using an older version than 1.12.2 and events work different in that version I suppose? The plugin supports version ranging from 1.12.2 to the latest release. Can you tell me what MInecraft version is the server running?

paper 1.12.2

**Comment by rudynakodach** [comment]
Did you try updating again? From version v2.1 there were 3 udpates. Can you please update to the latest version and tell me if the issue persists? Also, please send the whole stack as text and not just a part of it as a screenshot (it is not that helpful). The most important part is the `NullPointerException` (top of the screenshot you provided) that is probably the cause of the error.

The best thing you can do is to upload your whole server log [here](https://pastebin.com/) and send the paste link back so it's easier for me to see what's wrong with the plugin. 

Please provide more info, and I will get to work as fast as possible.
