### ISSUE TITLE
WI Bug Report

### ISSUE THREAD

**Issue by vovamod** [rudynakodach/WebhookIntegrations#7]
# Update (when ther is nothing)

Version of plugin (3.0)

![image](https://github.com/rudynakodach/WebhookIntegrations/assets/61664874/11fbe45b-6ad5-45fc-aa72-d6a283f544ed)

Expected behavior: No updates

**Comment by rudynakodach** [comment]
Hello.
The issue you are experiencing is a minor mistake I've made.
It should be fixed right now.

Let me know if you are experiencing any other problems as I'm happy to provide support.
