### ISSUE TITLE
WI Bug Report

### ISSUE THREAD

**Issue by TymekSL** [rudynakodach/WebhookIntegrations#9]
nie działa placeholder $time$ na discordzie.

**Comment by rudynakodach** [comment]
Placeholder **time** to nic innego jak czas serwera(HH:mm:ss). Wyślij screenshota i samego JSONa który jest wysyłany.

**Comment by TymekSL** [comment]
no to chyba coś ci nie działa, nic nie zmieniałem $time$ i to samo się pokazuje na discord

**Comment by rudynakodach** [comment]
Wyślij mi screenshota i config.
